---
title: "grade"
author: "Jae Yeon Kim"
date: "`r Sys.Date()`"
output: html_document
---

1. Install pkgs and load data

```{r}
# install pkgs 
if(!require(pacman)) install.packages("pacman")

pacman::p_load(tidyverse, here, ggthemes, patchwork, glue)

# load data 
df <- read_csv(here("assignments", "grades.csv"))
```

2. Visualize data

2.1. Assignment1

```{r}
df <- df %>%
  mutate(A1_alt = case_when(
    A1 <= 50 ~ 50, 
    A1 >= 51 & A1 <= 70 ~ 70, 
    A1 >= 71 ~ 100)) %>%
  pivot_longer(c("A1", "A1_alt"),
               names_to = "category",
               values_to = "grade") 

df %>%
  arrange(KorName) %>%
  filter(category == "A1_alt") %>%
  select(KorName, grade, everything())
```

```{r}
hist_plot <- df %>%
  ggplot(aes(x = grade, fill = category)) +
  geom_histogram(alpha = 0.3, position = position_dodge2()) +
  theme_economist() +
  labs(x = "", 
       y = "Count")

bar_plot <- df %>%
  group_by(category) %>%
  summarize(avg_grade = mean(grade)) %>%
  ggplot(aes(x = category, y = avg_grade)) +
  geom_col() +
  geom_text(aes(label = round(avg_grade, 2), col = "red"), size = 8) +
  theme_economist() +
  labs(x = "", 
       y = "Avg grade") +
  theme(legend.position = "none")

hist_plot + bar_plot

ggsave(here("outputs", "ass1.png"), width = 8, height = 8)
```
